name: Build and Push Necesse Server

on:
  workflow_dispatch:
    inputs:
      server_url:
        description: 'URL to Necesse Linux server binaries (zip file)'
        required: true
        type: string
      image_tags:
        description: 'Docker image tags (comma-separated, e.g., latest,v1.0.0,stable)'
        required: false
        default: 'latest'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/necesse-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: prepare-tags
        run: |
          TAGS="${{ inputs.image_tags }}"
          # Convert comma-separated tags to newline format for metadata-action
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" | tr ',' '\n' | while read tag; do
            if [ ! -z "$tag" ]; then
              echo "type=raw,value=$tag"
            fi
          done
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.prepare-tags.outputs.tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            SERVER_URL=${{ inputs.server_url }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image details
        run: |
          echo "### Docker Image Built Successfully! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** \`${{ inputs.image_tags }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Server URL:** \`${{ inputs.server_url }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Run the server with:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "docker run -it --rm \\" >> $GITHUB_STEP_SUMMARY
          echo "  -p 14159:14159/tcp \\" >> $GITHUB_STEP_SUMMARY
          echo "  -p 14159:14159/udp \\" >> $GITHUB_STEP_SUMMARY
          echo "  -v ./necesse-worlds:/root/.config/Necesse/saves/worlds \\" >> $GITHUB_STEP_SUMMARY
          FIRST_TAG=$(echo "${{ inputs.image_tags }}" | cut -d',' -f1)
          echo "  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${FIRST_TAG}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
